baseURL = "https://Jeffcfchang.github.io"
languageCode = "zh"
DefaultContentLanguage = "zh"
title = "Website of MR.Chefu"
theme = "anatole"
summarylength = 6
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm MR.Chefu"
author = "FBT小蜜圈"
description = "煉金鍊心，存乎一心"
profilePicture = "images/chefu.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/chefuchang/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/JeffCFChang"


[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:mr.chefu@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"